# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='昵称')),
                ('accountNumber', models.CharField(max_length=50, verbose_name='账户')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('status', models.CharField(max_length=5, verbose_name='状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': '用户',
            },
        ),
    ]
